/* Replace with your SQL commands */
ALTER TABLE schools
    ALTER COLUMN lat DROP NOT NULL,
    ALTER COLUMN lng DROP NOT NULL;

ALTER TABLE schools
    ALTER COLUMN lat TYPE DOUBLE PRECISION,
    ALTER COLUMN lng TYPE DOUBLE PRECISION;

ALTER TABLE schools
    ADD COLUMN status VARCHAR(255) DEFAULT 'pending';
    